### ISSUE TITLE
TypeError: createRouterMock is not a function

### ISSUE THREAD

**Issue by antlionguard** [posva/vue-router-mock#126]
### Reproduction
I've installed the "vue-router-mock" package and I created "jest.setup.js" file as in the documentation and i got the error after running a test.

Jest throws the following error.

`TypeError: createRouterMock is not a function.`

### Steps to reproduce the behavior

Dev Dependencies:

- "vue-router-mock": "0.0.3"
- "@jest/types": "^27.0.2"
- "@vue/test-utils": "2.0.0-rc.15"
- "vue-jest": "^5.0.0-0"
- "typescript": "~4.1.5"

### Expected behavior

Tests pass with no error.

### Actual behavior

    TypeError: createRouterMock is not a function
      3 |
      4 | // create one router per test file
    > 5 | const router = createRouterMock();
        |                ^
      6 | beforeEach(() => {
      7 |   injectRouterMock(router);
      8 | });

      at Object.<anonymous> (tests/unit/jest.setup.js:5:16)
          at Array.forEach (<anonymous>)

### Additional information

I've tried another "@vue/test-utils" versions(2.0.0-0, 2.0.0-rc.4) but i got same error.

**Comment by posva** [comment]
You need to import it . If that's not it, please provide a boiled down reproduction with updated dependencies (e.g. TS)

**Comment by antlionguard** [comment]
> You need to import it . If that's not it, please provide a boiled down reproduction with updated dependencies (e.g. TS)

I've already imported. Here's my jest.setup.ts:

```js
const { config } = require("@vue/test-utils");
const { VueRouterMock, createRouterMock, injectRouterMock } = require("vue-router-mock");

// create one router per test file
const router = createRouterMock();
beforeEach(() => {
  injectRouterMock(router);
});

// Add properties to the wrapper
config.plugins.VueWrapper.install(VueRouterMock);

```

And i didn't understand second sentence. I'm trying with updated packages like Typescript@4.4.3 but i got same error.

**Comment by antlionguard** [comment]
Hey, i found the problem.

If you have "vue-router" map in "moduleNameMapper" in jest.config.js like this:
#### **`jest.config.js`**
```json

moduleNameMapper: {
   "vue-router": "<rootDir>/node_modules/vue-router/",
}

```

"vue-router-mock" throws "TypeError: createRouterMock is not a function" error. I've removed and there's no error here. :)
