### ISSUE TITLE
"Symbol(router)" not found (regression with vue-router v4.1)

### ISSUE THREAD

**Issue by cexbrayat** [posva/vue-router-mock#165]
### Reproduction

Tests using vue-router-mock fail when upgrading vue-router from v4.0.16 to v4.1

Hello.vue
```vue
<script setup lang="ts">
import { useRouter } from 'vue-router';

const router = useRouter();
function navigate() {
  router.push('/');
}
</script>

<template>
  <button @click="navigate()">Home</button>
</template>
```

basic.test.ts
```ts
import { mount } from '@vue/test-utils';
import { createRouterMock, injectRouterMock } from 'vue-router-mock';
import Hello from '../components/Hello.vue';

test('mount component', async () => {
  expect(Hello).toBeTruthy();

  const router = createRouterMock({
    spy: {
      create: (fn) => vi.fn(fn),
      reset: (spy) => spy.restore(),
    },
  });
  injectRouterMock(router);
  const wrapper = mount(Hello);

  await wrapper.get('button').trigger('click');

  expect(router.push).toHaveBeenCalledWith('/');
});
```

### Steps to reproduce the behavior

Repro using this test and component

https://stackblitz.com/edit/vitest-dev-vitest-ttnyxb

The test succeeds. 
Bump the router to v4.1.0 in the package.json and run `npm install && npm run test` again

### Expected behavior

The test should still succeed

### Actual behavior

The test fails with:
```
stderr | test/basic.test.ts > mount component
[Vue warn]: injection "Symbol(router)" not found. 
  at <Hello ref="VTU_COMPONENT" > 
  at <VTUROOT>
```

**Comment by posva** [comment]
The test passes in the stackblitz. I also tried having this test locally and it passes 0376b08

**Comment by cexbrayat** [comment]
@posva It passes with vue-router v4.0.16. If you update to v4.1.0, then it fails.

**Comment by posva** [comment]
so this is actually a problem in vue-router
