### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by Essam-Harrous** [posva/vue-router-mock#195]
### Reproduction

I have used the library to mock the vue router behaviour in my test and followed the steps in readme file, in general everything starts working pretty well, I managed to check the `wrapper.router` object functions, but when I run the test I got this bug that says `Cannot read properties of undefined (reading 'push')` in this line of my code
` router.push('/dashboard') `.

### Steps to reproduce the behavior

1. run the test

### Additional information

![image](https://github.com/posva/vue-router-mock/assets/53625910/900c48c8-0d05-481a-ad93-b8b5a78927c3)

**Comment by posva** [comment]
You are probably missing some of the installation steps but I cannot check with a boiled down reproduction
