### ISSUE TITLE
`initialLocation` doesn't support what router.push() supports

### ISSUE THREAD

**Issue by matthew-dean** [posva/vue-router-mock#196]
### Reproduction

The documentation says: 

> initialLocation accepts anything that can be passed to router.push().

However, this results in an error:
```ts
const router = createRouterMock({
    initialLocation: {
      name: 'Reports',
      params: {
        domain: 'example.com',
        code: 'code'
      }
    }
  })
```
...but this does not:
```ts
await router.push({
      name: 'Reports',
      params: {
        domain: 'example.com',
        code: 'code'
      }
    })
```
The error with the first one is:
```ts
Serialized Error: {
  "location": {
    "name": "Reports",
    "params": {
      "code": "code",
      "domain": "example.com",
    },
  },
}
```

(To be fair, the `router.push()` code also doesn't work when I try to use: 
```
const route = useRoute()
const aliasDomain = String(route.params.domain)
```
...which I'm still trying to figure out?

**Comment by posva** [comment]
I can't know what's wrong with just this info but maybe you are using artificial params? See https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22

Remember to use the [Discord chat](https://chat.vuejs.org/) to ask questions!
