### ISSUE TITLE
add functions to easily set params

### ISSUE THREAD

**Issue by cexbrayat** [posva/vue-router-mock#42]
### What problem is this solving

If a component accesses the route params, it is fairly common in a unit test to set the params of the current route to some dummy values:

```ts
getRouter().currentRoute.value.params = {
  userId: '12'
};
```

### Proposed solution

Maybe there is an easier way to do this?
If not, what do you think about introducing a method like `setCurrentRouteParams({ userId: '12' })`?

I'm willing to open a PR if you agree and settle for a (better?) name/API.

**Comment by posva** [comment]
Yeah, this looks like a good idea:

- updateParams
- setParams
- updateQuery
- setQuery
- setHash

Although you should be able to do `router.push({ query, hash })` but not for params if the route cannot be correctly resolved

**Comment by cexbrayat** [comment]
Sounds good 👍
I can try adding `setParams`, `setQuery` and `setHash` to begin (I'll try to open a PR tomorrow)

**Comment by posva** [comment]
Cool, thanks!
